# 对异常进行捕获与抛出

## 捕获异常
在Java中，凡是可能抛出异常的语句，都可以用try ... catch捕获。把可能发生异常的语句放在try { ... }中，然后使用catch捕获对应的Exception及其子类    

### 多catch语句 
我们可以使用一个try以及多个catch来捕获对应的Exception及其子类   
JVM在捕获到异常后，会从上到下匹配catch语句，匹配到某个catch后，执行catch代码块，然后不再继续匹配    
> 简单来说就是从上到下找解决方案，找到了就不去找其他的方案了    
> 多个catch只能有一个能被执行

```Java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println(e);
    } catch (NumberFormatException e) {
        System.out.println(e);
    }
}
```

因为**从上到下查找**的机制，所以我们安排```catch```的顺序是十分重要的，特别是**必须把子类写在前面** 
如果我们不这么做，子类的异常是永远不会捕获到的：因为它的父类(比如IOException)总是有比它更大的范围，如果父类在前，肯定就直接使用父类catch的方案了    

所以，上面的代码的更正确的写法应该是：
```Java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
    } catch (IOException e) {
        System.out.println("IO error");
    }
}
```

### Finally语句
> 论是否有异常发生，我们都希望执行的一些语句       

````finally```语句块保证有无错误都会执行    

```Java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (UnsupportedEncodingException e) {
        System.out.println("Bad encoding");
    } catch (IOException e) {
        System.out.println("IO error");
    } finally {
        System.out.println("END");
    }
```

Finally具有以下几个特点:
1.finally语句不是必须的，可写可不写；
2.finally**总是最后执行**   

> 某些情况下，可以没有catch，只使用try ... finally结构。这种事情一般发生在方法声明了可抛出异常的时候————此时我们只需要做好try和finally即可  

### 捕获多种异常
如果某些异常的处理逻辑相同，但是异常本身不存在继承关系，那么就得编写多条catch子句   
不过此时如果发现某些子句具有相同的执行逻辑，那么就可以利用```|```将它们合二为一 

```Java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException e) {
        System.out.println("Bad input");
    } catch (NumberFormatException e) {
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}
```

这时候发现```IOException```与```NumberFormatException```的处理代码是相同的，那么我们就可以把它们合在一起。于是代码可以修改为:
```Java
public static void main(String[] args) {
    try {
        process1();
        process2();
        process3();
    } catch (IOException | NumberFormatException e) { 
        // IOException或NumberFormatException
        System.out.println("Bad input");
    } catch (Exception e) {
        System.out.println("Unknown error");
    }
}
```

## 抛出异常